dist: xenial

language: python

sudo: false

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install pytest coverage coveralls six

script:
  - coverage run --source=makeapp setup.py test

after_success:
  - coveralls
