dist: xenial

language: python

sudo: false

python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

install:
  - pip install pytest coverage coveralls six

script:
  - coverage run --source=makeapp setup.py test

after_success:
  - coveralls
