site_name: makeapp
site_url: !ENV READTHEDOCS_CANONICAL_URL

copyright: Copyright &copy; 2013-2025, Igor Starikov

repo_url: https://github.com/idlesign/makeapp
edit_uri: edit/master/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/idlesign

plugins:
  - search
  - navsorted

theme:
  name: material
  palette:
    primary: green
  features:
    - navigation.top
    - toc.follow
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
